server:
  port: 8787
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: zuul-api-gateway
  cloud:
    gateway:
      routes:
        - id: eureka-server
          uri: lb://eureka-server
          predicates:
            - Path=/employee/**
        - id: ATM-Locator
          uri: lb://ATM-Locator
          predicates:
            - Path=/locations/**
        - id: postalCode
          uri: lb://ATM-Locator
          predicates:
            - Path=/postalCode/**


